version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - .:/home
